### ISSUE TITLE
HTML language NL 

### ISSUE THREAD

**Issue by TessaViergever** [Stefan-Espant/the-startup-responsive-interactieve-website#10]
Hi,

Ik zag dat je HTML doc op Nederlands staat, wellicht is Engels een betere optie? (:

https://github.com/Stefan-Espant/the-startup-responsive-interactieve-website/blob/eed78d128f662552a07d2484e53484784e4bd7be/index.html#L2

**Comment by Stefan-Espant** [comment]
Hi Tessa, 
De html language heeft betrekking tot de content van de pagina.
Bedankt voor je alertheid!
