### ISSUE TITLE
Haal al je SVG's door SVGOMG

### ISSUE THREAD

**Issue by ju5tu5** [Stefan-Espant/the-startup-responsive-interactieve-website#13]
https://github.com/Stefan-Espant/the-startup-responsive-interactieve-website/blob/eed78d128f662552a07d2484e53484784e4bd7be/index.html#L79-L105

https://jakearchibald.github.io/svgomg/

**Comment by Stefan-Espant** [comment]
Whuttt, vet goeie tool!
Ik ga het gelijk gebruiken.
