### ISSUE TITLE
Overbodige streepjes

### ISSUE THREAD

**Issue by ju5tu5** [Stefan-Espant/the-startup-responsive-interactieve-website#14]
https://github.com/Stefan-Espant/the-startup-responsive-interactieve-website/blob/eed78d128f662552a07d2484e53484784e4bd7be/index.html#L214

Deze kan je beter met de li aangeven.. hoeft niet in tekst

**Comment by Stefan-Espant** [comment]
De tekst kreeg ik aangeleverd en heb ik verder geen invloed op gehad. In de nieuwe versie is het opgelost
