### ISSUE TITLE
Width van de carrousel

### ISSUE THREAD

**Issue by Demivdm** [Stefan-Espant/the-startup-responsive-interactieve-website#15]
https://github.com/Stefan-Espant/the-startup-responsive-interactieve-website/blob/eed78d128f662552a07d2484e53484784e4bd7be/style/main.css#L198

De afbeeldingen van de carrousel vullen niet het volledige scherm (bij de mobiele versie) door de width die bij .images staat.

**Comment by Stefan-Espant** [comment]
Done.
