### ISSUE TITLE
<strong> als styling?

### ISSUE THREAD

**Issue by TessaViergever** [Stefan-Espant/the-startup-responsive-interactieve-website#17]
Hoii,

Ik zag dat je <strong> gebruikt hebt in de HTML, wellicht zou je het element kunnen stylen in CSS?

https://github.com/Stefan-Espant/the-startup-responsive-interactieve-website/blob/eed78d128f662552a07d2484e53484784e4bd7be/index.html#L154

**Comment by Stefan-Espant** [comment]
Bedankt voor je feedback.
