### ISSUE TITLE
Design schaalt terug bij <400px

### ISSUE THREAD

**Issue by ju5tu5** [Stefan-Espant/the-startup-responsive-interactieve-website#2]
<img width="517" alt="image" src="https://user-images.githubusercontent.com/140124/212281839-1b249941-85af-407c-a68d-577e8729a50f.png">
Er is iets geks op smaller dan 400px schermen, zie de witruimte aan de rechterkant.

**Comment by ju5tu5** [comment]
Ow en het start bij 350px-ish

**Comment by Stefan-Espant** [comment]
Gefixt!
