### ISSUE TITLE
design: lazy loaded afbeeldingen

### ISSUE THREAD

**Issue by ju5tu5** [Stefan-Espant/the-startup-responsive-interactieve-website#23]
Ik zag een flash of unstyled content bij de afbeeldingen. Het is goed om srcset en sizes op je afbeeldingen te plaatsen, de browser kan dan zelf bepalen welke resolutie het beste past. Ook een goed idee om alvast een grijze achtergrondkleur te gebruiken. Als je dat toepast verwacht de gebruiker daar al iets ook als het nog niet is ingeladen. 
<img width="514" alt="image" src="https://user-images.githubusercontent.com/140124/213660069-b258eade-88e6-40ac-9fa7-5c2903519963.png">

**Comment by Stefan-Espant** [comment]
Changed.
