### ISSUE TITLE
Images wellicht te klein?

### ISSUE THREAD

**Issue by sannevanseeventer** [Stefan-Espant/the-startup-responsive-interactieve-website#26]
Afbeeldingen van hoe het huis er van binnen uitziet zijn best klein. Als koper wil je dat graag ook goed kunnen. 

<img width="1436" alt="Schermafbeelding 2023-01-20 om 10 22 35" src="https://user-images.githubusercontent.com/112857444/213660367-67ee138b-ea65-4aff-9151-2e0cf601e1d1.png">

**Comment by Stefan-Espant** [comment]
Done
