### ISSUE TITLE
desktop hero afbeelding

### ISSUE THREAD

**Issue by tom-2810** [Stefan-Espant/the-startup-responsive-interactieve-website#31]
De afbeelding binnen de hero section neemt veel ruimte in beslag.

Je zou misschien de afbeelding wat kleiner kunnen maken, waardoor de rest van de gallery rechts in beeld kan.

![Schermafbeelding_20230120_102126](https://user-images.githubusercontent.com/112861614/213660512-08098cd5-237f-4433-8b40-e546b3c80986.png)

**Comment by Stefan-Espant** [comment]
Thanks voor je feedback. Hij is goed zo.
