### ISSUE TITLE
Footer content

### ISSUE THREAD

**Issue by sannevanseeventer** [Stefan-Espant/the-startup-responsive-interactieve-website#32]
Op desktop staan de footer content onder elkaar, misschien mooi om deze in meerdere columns te verdelen over de gehele breedte. 

<img width="1482" alt="Schermafbeelding 2023-01-20 om 10 25 09" src="https://user-images.githubusercontent.com/112857444/213660914-5309b101-3de7-4ed8-83ac-776ca32bbb73.png">

**Comment by Stefan-Espant** [comment]
Footer is aangepast, toegankelijk en responsive
