### ISSUE TITLE
kaart voelt squashed op klein scherm

### ISSUE THREAD

**Issue by ju5tu5** [Stefan-Espant/the-startup-responsive-interactieve-website#34]
Op klein scherm is de kaart een beetje ingedrukt. Elementen mogen ruimte innemen.

<img width="507" alt="image" src="https://user-images.githubusercontent.com/140124/213661099-efb37d0f-4e95-404a-9b83-99b9ab04624b.png">

**Comment by Stefan-Espant** [comment]
Done.
