### ISSUE TITLE
Uitlijning

### ISSUE THREAD

**Issue by chaanw** [Stefan-Espant/the-startup-responsive-interactieve-website#35]
De verschillende blokken zijn niet met elkaar uitgelijnd waardoor het design heel erg schommelt. Hierdoor oogt het heel onrustig

<img width="406" alt="Scherm­afbeelding 2023-01-20 om 10 27 08" src="https://user-images.githubusercontent.com/90189679/213661269-dfa6ac90-d1ff-4cc3-95b0-efee9009095e.png">

**Comment by Stefan-Espant** [comment]
Done
