### ISSUE TITLE
subtitles een andere kleur? 

### ISSUE THREAD

**Issue by sannevanseeventer** [Stefan-Espant/the-startup-responsive-interactieve-website#36]
Bij bijvoorbeeld "Oppervlakten en inhoud" staat een subtitle "gebruiksoppervlakten". Misschien mooier als deze een andere kleur heeft om meer onderscheid te maken. 

<img width="670" alt="Schermafbeelding 2023-01-20 om 10 26 16" src="https://user-images.githubusercontent.com/112857444/213661635-4da5eb0d-59de-4f31-a1a9-a2637e363701.png">

**Comment by Stefan-Espant** [comment]
h2 een grotere `font-size gegeven` Thanks!
