### ISSUE TITLE
Responsiveness kan beter

### ISSUE THREAD

**Issue by chaanw** [Stefan-Espant/the-startup-responsive-interactieve-website#39]
Er gaat het eea mis als je de pagina groter/kleiner maakt. 

<img width="1609" alt="Scherm­afbeelding 2023-01-20 om 10 29 19" src="https://user-images.githubusercontent.com/90189679/213662151-a0b85565-fdb7-4e19-8393-f9c101dcda2e.png">

**Comment by Stefan-Espant** [comment]
Website responsive tot 1440px
