### ISSUE TITLE
Design: iets meer ruimte tussen tekst

### ISSUE THREAD

**Issue by ju5tu5** [Stefan-Espant/the-startup-responsive-interactieve-website#4]
Je kunt nog iets met margins/padding doen want het staat nu te dicht op elkaar.
<img width="281" alt="image" src="https://user-images.githubusercontent.com/140124/212282158-b6bcfa5d-6dc8-4a28-a695-6ce11f877888.png">

**Comment by Stefan-Espant** [comment]
Inline-height van de `p` staat nu op 1.4em ingesteld!
