### ISSUE TITLE
Tekst onderverdelen met bijv li items

### ISSUE THREAD

**Issue by sannevanseeventer** [Stefan-Espant/the-startup-responsive-interactieve-website#41]
Misschien mooi om bijvoorbeeld de woningindeling meer qua tekst onder te verdelen, ipv 1 lap tekst.

**Comment by Stefan-Espant** [comment]
Omschrijving is goed zo. Details heb ik verwerkt in een description list `<dl>` met description titles `<dt>` en een description detail `<dd>`
