### ISSUE TITLE
Afstanden van de kopjes mogen duidelijker

### ISSUE THREAD

**Issue by chaanw** [Stefan-Espant/the-startup-responsive-interactieve-website#43]
De kopjes mogen wat verder af van de blokken erboven, zowel binnen het kader als erbuiten. Het is nu een beetje onduidelijk welk kopje waarbij hoort.

<img width="667" alt="Scherm­afbeelding 2023-01-20 om 10 38 30" src="https://user-images.githubusercontent.com/90189679/213663786-563e97f7-61f1-4e40-a35c-fce85f18aff8.png">

**Comment by Stefan-Espant** [comment]
FIxed.
