### ISSUE TITLE
Afbeelding half weg

### ISSUE THREAD

**Issue by Maaike0904** [Stefan-Espant/the-startup-responsive-interactieve-website#5]
<img width="406" alt="Schermafbeelding 2023-01-13 om 10 09 59" src="https://user-images.githubusercontent.com/112861144/212282159-ec972872-5223-4bca-a048-ad707bbd7ed8.png">
Rechter afbeelding zie je maar voor de helft

**Comment by Stefan-Espant** [comment]
Done.
