### ISSUE TITLE
Kapitalen

### ISSUE THREAD

**Issue by Maaike0904** [Stefan-Espant/the-startup-responsive-interactieve-website#6]
<img width="106" alt="Schermafbeelding 2023-01-13 om 10 10 15" src="https://user-images.githubusercontent.com/112861144/212282305-75fdba54-86be-4132-b784-737f1852d258.png">
<img width="118" alt="Schermafbeelding 2023-01-13 om 10 10 21" src="https://user-images.githubusercontent.com/112861144/212282312-49d08eee-00a4-45ad-ad1f-842f29d39075.png">
Wanneer kapitalen en wanneer niet?

**Comment by Stefan-Espant** [comment]
De kapitalen zijn door de makelaar gemaakt. Vrij nutteloos inderdaad en zijn daarom gefixt.
