### ISSUE TITLE
Hover is een beetje klein

### ISSUE THREAD

**Issue by FouadTaissate** [Stefan-Espant/the-startup-responsive-interactieve-website#8]
<img width="74" alt="image" src="https://user-images.githubusercontent.com/112860051/212282177-6f59be01-0d85-4980-8874-290f9e5c26c3.png">
<img width="86" alt="image" src="https://user-images.githubusercontent.com/112860051/212282235-ad583699-1504-412e-a15e-da1b972c7d7a.png">

**Comment by Stefan-Espant** [comment]
Ik heb er een 
```css 
display: block;
``` 
aangegeven en is nu opgelost.
